import { defineStore } from 'pinia'
import { useProjectsStore } from './projects'

export const useSkillsStore = defineStore('skills', {
  state: () => ({
    categories: [
      {
        name: 'frontend',
        title: '前端開發',
        icon: '💻',
      },
      {
        name: 'backend',
        title: '後端開發',
        icon: '⚡',
      },
      {
        name: 'database',
        title: '資料庫',
        icon: '💾',
      },
      {
        name: 'cloud',
        title: '雲端服務',
        icon: '☁️',
      },
      {
        name: 'ai',
        title: '人工智慧',
        icon: '🤖',
      },
      {
        name: 'devops',
        title: 'DevOps',
        icon: '🔍',
      },
      {
        name: 'design',
        title: '設計工具',
        icon: '🎨',
      },
    ],
    skills: [
      {
        name: 'Vue.js',
        icon: 'vue',
        category: 'frontend',
        level: 90,
        description: '主要的前端開發框架，擅長使用 Vue 3 Composition API 開發大型應用',
        experience: '3年以上開發經驗',
      },
      {
        name: 'TypeScript',
        icon: 'ts',
        category: 'frontend',
        level: 85,
        description: '在所有前端專案中使用 TypeScript 提升程式碼品質和開發效率',
        experience: '2年以上開發經驗',
      },
      {
        name: 'Tailwind CSS',
        icon: 'tailwind',
        category: 'frontend',
        level: 85,
        description: '熟練運用 Tailwind CSS 開發現代化的響應式網頁介面',
        experience: '2年以上開發經驗',
      },
      {
        name: 'Node.js',
        icon: 'nodejs',
        category: 'backend',
        level: 80,
        description: '使用 Node.js 開發高效能的後端服務和 API',
        experience: '2年以上開發經驗',
      },
      {
        name: 'Python',
        icon: 'python',
        category: 'backend',
        level: 75,
        description: '使用 Python 開發後端服務和資料處理應用，具備良好的程式設計能力',
        experience: '2年開發經驗',
      },
      {
        name: 'Express',
        icon: 'express',
        category: 'backend',
        level: 80,
        description: '使用 Express.js 建構 RESTful API 和後端服務',
        experience: '2年開發經驗',
      },
      {
        name: 'PostgreSQL',
        icon: 'postgres',
        category: 'database',
        level: 85,
        description: '熟練使用 PostgreSQL 設計和優化資料庫結構，具備效能調校經驗',
        experience: '2年以上使用經驗',
      },
      {
        name: 'MySQL',
        icon: 'mysql',
        category: 'database',
        level: 80,
        description: '具備 MySQL 資料庫設計和管理能力，熟悉效能優化',
        experience: '2年使用經驗',
      },
      {
        name: 'MongoDB',
        icon: 'mongodb',
        category: 'database',
        level: 75,
        description: '使用 MongoDB 開發非關聯式資料庫應用，適合處理大量非結構化資料',
        experience: '1年使用經驗',
      },
      {
        name: 'Git',
        icon: 'git',
        category: 'devops',
        level: 90,
        description: '精通 Git 版本控制，具備團隊協作和分支管理經驗',
        experience: '3年以上使用經驗',
      },
      {
        name: 'GitHub',
        icon: 'github',
        category: 'devops',
        level: 85,
        description: '熟練使用 GitHub 進行專案管理和團隊協作',
        experience: '3年以上使用經驗',
      },
      {
        name: 'Docker',
        icon: 'docker',
        category: 'devops',
        level: 80,
        description: '使用 Docker 容器化應用程式，具備基礎設施即代碼經驗',
        experience: '2年使用經驗',
      },
      {
        name: 'PyTorch',
        icon: 'pytorch',
        category: 'ai',
        level: 70,
        description: '使用 PyTorch 開發深度學習模型，具備基礎的神經網路設計能力',
        experience: '1年使用經驗',
      },
      {
        name: 'TensorFlow',
        icon: 'tensorflow',
        category: 'ai',
        level: 65,
        description: '使用 TensorFlow 進行機器學習模型訓練和部署',
        experience: '1年使用經驗',
      },
      {
        name: 'Scikit-learn',
        icon: 'sklearn',
        category: 'ai',
        level: 75,
        description: '使用 Scikit-learn 進行數據分析和機器學習模型開發',
        experience: '1.5年使用經驗',
      },
      {
        name: 'Bootstrap',
        icon: 'bootstrap',
        category: 'frontend',
        level: 85,
        description: '熟練使用 Bootstrap 開發響應式網頁介面',
        experience: '2年使用經驗',
      },
      {
        name: 'CSS',
        icon: 'css',
        category: 'frontend',
        level: 90,
        description: '精通 CSS3 技術，能夠實現複雜的網頁布局和動畫效果',
        experience: '3年以上使用經驗',
      },
      {
        name: 'HTML',
        icon: 'html',
        category: 'frontend',
        level: 95,
        description: '精通 HTML5 標準，注重語義化標籤和無障礙網頁開發',
        experience: '3年以上使用經驗',
      },
      {
        name: 'Figma',
        icon: 'figma',
        category: 'design',
        level: 75,
        description: '使用 Figma 進行網頁和應用程式的介面設計',
        experience: '1年使用經驗',
      },
      {
        name: 'Firebase',
        icon: 'firebase',
        category: 'cloud',
        level: 70,
        description: '使用 Firebase 開發即時應用和後端服務',
        experience: '1年使用經驗',
      },
      {
        name: 'Github Actions',
        icon: 'githubactions',
        category: 'devops',
        level: 80,
        description: '使用 GitHub Actions 實現持續整合和部署流程',
        experience: '1.5年使用經驗',
      },
      {
        name: 'JavaScript',
        icon: 'js',
        category: 'frontend',
        level: 90,
        description: '精通 JavaScript ES6+ 特性，具備豐富的前端開發經驗',
        experience: '3年以上使用經驗',
      },
      {
        name: 'LaTeX',
        icon: 'latex',
        category: 'devops',
        level: 70,
        description: '使用 LaTeX 編寫技術文檔和學術論文',
        experience: '1年使用經驗',
      },
      {
        name: 'Markdown',
        icon: 'md',
        category: 'devops',
        level: 85,
        description: '熟練使用 Markdown 編寫文檔和技術筆記',
        experience: '2年使用經驗',
      },
      {
        name: 'Matlab',
        icon: 'matlab',
        category: 'devops',
        level: 65,
        description: '使用 Matlab 進行數值計算和數據分析',
        experience: '1年使用經驗',
      },
      {
        name: 'nginx',
        icon: 'nginx',
        category: 'backend',
        level: 75,
        description: '配置和管理 Nginx 伺服器，實現負載均衡和反向代理',
        experience: '1.5年使用經驗',
      },
      {
        name: 'Pinia',
        icon: 'pinia',
        category: 'frontend',
        level: 85,
        description: '使用 Pinia 管理 Vue.js 應用的狀態',
        experience: '1.5年使用經驗',
      },
      {
        name: 'Sequelize',
        icon: 'sequelize',
        category: 'database',
        level: 80,
        description: '使用 Sequelize ORM 進行資料庫操作和模型設計',
        experience: '2年使用經驗',
      },
      {
        name: 'Three.js',
        icon: 'threejs',
        category: 'frontend',
        level: 70,
        description: '使用 Three.js 開發 3D 網頁應用',
        experience: '1年使用經驗',
      },
      {
        name: 'Vercel',
        icon: 'vercel',
        category: 'cloud',
        level: 80,
        description: '使用 Vercel 部署和管理前端應用',
        experience: '1.5年使用經驗',
      },
      {
        name: 'Vite',
        icon: 'vite',
        category: 'frontend',
        level: 85,
        description: '使用 Vite 建構現代化的前端開發環境',
        experience: '1.5年使用經驗',
      },
      {
        name: 'Vuetify',
        icon: 'vuetify',
        category: 'frontend',
        level: 80,
        description: '使用 Vuetify UI 框架開發現代化的網頁應用',
        experience: '2年使用經驗',
      },
    ],
  }),
  getters: {
    getSkillProjects() {
      const projectsStore = useProjectsStore()
      return (skillName: string) => {
        return projectsStore.projects
          .filter((project) => project.tags.includes(skillName))
          .map((project) => project.title)
      }
    },
  },
})
